//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriarSolicitacaoRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class CriarSolicitacaoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSolicitacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioSolicitanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSolicitacao {
            get {
                return this.TipoSolicitacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSolicitacaoField, value) != true)) {
                    this.TipoSolicitacaoField = value;
                    this.RaisePropertyChanged("TipoSolicitacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioSolicitante {
            get {
                return this.UsuarioSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioSolicitanteField, value) != true)) {
                    this.UsuarioSolicitanteField = value;
                    this.RaisePropertyChanged("UsuarioSolicitante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriarSolicitacaoResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class CriarSolicitacaoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObterSolicitacaoRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class ObterSolicitacaoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObterSolicitacaoResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class ObterSolicitacaoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.SolicitacaoDto SolicitacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.SolicitacaoDto Solicitacao {
            get {
                return this.SolicitacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitacaoField, value) != true)) {
                    this.SolicitacaoField = value;
                    this.RaisePropertyChanged("Solicitacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitacaoDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class SolicitacaoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCriacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataProcessamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoProcessamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSolicitacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioSolicitanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCriacao {
            get {
                return this.DataCriacaoField;
            }
            set {
                if ((this.DataCriacaoField.Equals(value) != true)) {
                    this.DataCriacaoField = value;
                    this.RaisePropertyChanged("DataCriacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataProcessamento {
            get {
                return this.DataProcessamentoField;
            }
            set {
                if ((this.DataProcessamentoField.Equals(value) != true)) {
                    this.DataProcessamentoField = value;
                    this.RaisePropertyChanged("DataProcessamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultadoProcessamento {
            get {
                return this.ResultadoProcessamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoProcessamentoField, value) != true)) {
                    this.ResultadoProcessamentoField = value;
                    this.RaisePropertyChanged("ResultadoProcessamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSolicitacao {
            get {
                return this.TipoSolicitacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSolicitacaoField, value) != true)) {
                    this.TipoSolicitacaoField = value;
                    this.RaisePropertyChanged("TipoSolicitacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioSolicitante {
            get {
                return this.UsuarioSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioSolicitanteField, value) != true)) {
                    this.UsuarioSolicitanteField = value;
                    this.RaisePropertyChanged("UsuarioSolicitante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarSolicitacoesResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class ListarSolicitacoesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.SolicitacaoDto[] SolicitacoesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.SolicitacaoDto[] Solicitacoes {
            get {
                return this.SolicitacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitacoesField, value) != true)) {
                    this.SolicitacoesField = value;
                    this.RaisePropertyChanged("Solicitacoes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessarSolicitacaoRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class ProcessarSolicitacaoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessarSolicitacaoResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceDeskFiscal.SoapService")]
    [System.SerializableAttribute()]
    public partial class ProcessarSolicitacaoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoProcessamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultadoProcessamento {
            get {
                return this.ResultadoProcessamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoProcessamentoField, value) != true)) {
                    this.ResultadoProcessamentoField = value;
                    this.RaisePropertyChanged("ResultadoProcessamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SolicitacaoServiceReference.ISolicitacaoService")]
    public interface ISolicitacaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/CriarSolicitacao", ReplyAction="http://tempuri.org/ISolicitacaoService/CriarSolicitacaoResponse")]
        ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoResponse CriarSolicitacao(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/CriarSolicitacao", ReplyAction="http://tempuri.org/ISolicitacaoService/CriarSolicitacaoResponse")]
        System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoResponse> CriarSolicitacaoAsync(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/ObterSolicitacao", ReplyAction="http://tempuri.org/ISolicitacaoService/ObterSolicitacaoResponse")]
        ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoResponse ObterSolicitacao(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/ObterSolicitacao", ReplyAction="http://tempuri.org/ISolicitacaoService/ObterSolicitacaoResponse")]
        System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoResponse> ObterSolicitacaoAsync(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/ListarSolicitacoes", ReplyAction="http://tempuri.org/ISolicitacaoService/ListarSolicitacoesResponse")]
        ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ListarSolicitacoesResponse ListarSolicitacoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/ListarSolicitacoes", ReplyAction="http://tempuri.org/ISolicitacaoService/ListarSolicitacoesResponse")]
        System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ListarSolicitacoesResponse> ListarSolicitacoesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/ProcessarSolicitacao", ReplyAction="http://tempuri.org/ISolicitacaoService/ProcessarSolicitacaoResponse")]
        ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoResponse ProcessarSolicitacao(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitacaoService/ProcessarSolicitacao", ReplyAction="http://tempuri.org/ISolicitacaoService/ProcessarSolicitacaoResponse")]
        System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoResponse> ProcessarSolicitacaoAsync(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitacaoServiceChannel : ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ISolicitacaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitacaoServiceClient : System.ServiceModel.ClientBase<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ISolicitacaoService>, ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ISolicitacaoService {
        
        public SolicitacaoServiceClient() {
        }
        
        public SolicitacaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitacaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitacaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitacaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoResponse CriarSolicitacao(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoRequest request) {
            return base.Channel.CriarSolicitacao(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoResponse> CriarSolicitacaoAsync(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.CriarSolicitacaoRequest request) {
            return base.Channel.CriarSolicitacaoAsync(request);
        }
        
        public ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoResponse ObterSolicitacao(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoRequest request) {
            return base.Channel.ObterSolicitacao(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoResponse> ObterSolicitacaoAsync(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ObterSolicitacaoRequest request) {
            return base.Channel.ObterSolicitacaoAsync(request);
        }
        
        public ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ListarSolicitacoesResponse ListarSolicitacoes() {
            return base.Channel.ListarSolicitacoes();
        }
        
        public System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ListarSolicitacoesResponse> ListarSolicitacoesAsync() {
            return base.Channel.ListarSolicitacoesAsync();
        }
        
        public ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoResponse ProcessarSolicitacao(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoRequest request) {
            return base.Channel.ProcessarSolicitacao(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoResponse> ProcessarSolicitacaoAsync(ServiceDeskFiscal.SoapClient.SolicitacaoServiceReference.ProcessarSolicitacaoRequest request) {
            return base.Channel.ProcessarSolicitacaoAsync(request);
        }
    }
}
